<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
1팀 프로젝트 화이팅~! <br>
변경사항........
변경사항........
변경사항........
변경사항........
변경사항........
변경사항........
</body>
</html>